package model

// ClusterProfile signifies a cluster profile object.
type ClusterProfile struct {

	// ID is a unique identifier for the cluster in the watcher application
	// cluster id will be generated by the server to avoid cluster id conflict
	ID string `json:"id"`

	// Name is a user-given name for the cluster
	// The Name will be unique in the application and is a required field
	// for cluster profile creation
	Name string `json:"name" validate:"required"`

	// Endpoints is a list of URLs of nodes
	// This is a required field for cluster profile creation
	Endpoints []string `json:"endpoints"`

	// Username is a user name for authentication.
	Username string `json:"username"`

	// Password is a password for authentication.
	Password string `json:"password"`

	// TLS indicates whether to use tls certificates for authentication
	TLS bool `json:"tls"`

	// ServerName ensures the cert matches the given host in case of discovery / virtual hosting
	ServerName string `json:"server_name"`

	// The user will upload certificate file, key file and the ca file.
	// The files will be stored in the database and unique ids will be generated
	// for the certificates. CertFile, KeyFile, TrustedCAFile will hold the id
	// of the certificate files

	// CertFile is Certificate file name
	CertFile string `json:"cert_file"`

	// KeyFile is key file name
	KeyFile string `json:"key_file"`

	// TrustedCAFile is Certificate Authority file name
	TrustedCAFile string `json:"trusted_ca_file"`

	// CreationTime indicates the time when the cluster profile was created
	CreationTime int64 `json:"creation_time"`
}
