###
GET http://0.0.0.0:8080/api/auth/checkAdminStatus HTTP/1.1

###
POST http://0.0.0.0:8080/api/auth/saveAdminProfile HTTP/1.1
Content-Type: application/json

{
  "password": "16121996"
}

###
POST http://0.0.0.0:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "password": "16121996"
}