POST http://0.0.0.0:8080/api/cluster/create HTTP/1.1
Content-Type: application/json
Authorization: Auth eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE1OTg5Nzk4OTYsInVzZXJfaWQiOiJhZG1pbiJ9.z2FXA4lP4zKggA5el2X-I3nSndY6P_D2x53fOpxE-84

{
  "name" : "do",
  "endpoints" : ["http://159.65.149.70:2379"],
  "username" : "root",
  "password" : "16121996"
}


###
POST http://0.0.0.0:8080/api/cluster/fetch HTTP/1.1
Authorization: Auth eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE1OTg5Nzk4OTYsInVzZXJfaWQiOiJhZG1pbiJ9.z2FXA4lP4zKggA5el2X-I3nSndY6P_D2x53fOpxE-84